# MENGUASAI PYTHON TINGKAT PEMULA

# LIST

In [1]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [2]:
my_list + [4,5]
print(my_list)

[1, 2, 3]


In [3]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [13]:
my_list.append(4)
print(my_list)

[1, 2, 3, 4, 4]


In [14]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [15]:
my_list.extend([4,5,6])
print(my_list)

[1, 2, 3, 4, 5, 6]


In [18]:
my_list.remove(5)
print(my_list)

[1, 2, 3, 6]


# DICTIONARIES

In [1]:
student = {'name':'nadia','age':20}
student

{'name': 'nadia', 'age': 20}

In [2]:
employee = {'cto':{'name':'nadia','age':20}}
employee

{'cto': {'name': 'nadia', 'age': 20}}

In [3]:
student = dict(name='dia',age=22)
student

{'name': 'dia', 'age': 22}

In [5]:
print(student['name'])

dia


In [6]:
del student['age']
print(student)

{'name': 'dia'}


In [8]:
student = {'name':'nadia','age':20}
print(student.keys())

dict_keys(['name', 'age'])


In [9]:
print(student.values())

dict_values(['nadia', 20])


# TUPLES

In [10]:
people=('nadia',('kode','random'))
print(people)

('nadia', ('kode', 'random'))


In [11]:
print(people[0])

nadia


In [12]:
print(people[1])

('kode', 'random')


In [13]:
print(people[1][0])

kode


## slicing

In [14]:
numbers=(1,2,3,4)
new_numbers=numbers[0], numbers[1:3]
print(new_numbers)

(1, (2, 3))


## sorting

In [15]:
email_attr=('to','from','cc','bcc','subject','body')
email_attr_list=list(email_attr)
email_attr_list.sort()
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


# FILES

In [16]:
myfile=open('nad.txt','w')

### menambahkan text didalam file

In [17]:
myfile.write('hei you!\n')

9

In [18]:
myfile.write('see you!\n')

9

### menutup file

In [19]:
myfile.close()

### membuka kembali file

In [20]:
myfile=open('nad.txt')

In [21]:
myfile.readline()

'hei you!\n'

In [22]:
myfile.readline()

'see you!\n'

### membaca isi file secara keseluruhan

In [23]:
open('nad.txt').read()

'hei you!\nsee you!\n'

In [24]:
print(open('nad.txt').read())

hei you!
see you!



### menambahkan isi file dengan berbagai tipe data

In [25]:
x,y,z=43,44,45
message='spam'
data={'a':1,'b':2}
list=[1,2,3]
file=open('nad.txt','w')
file.write(message + '\n')

5

In [28]:
file.write('%s,%s,%s\n' % (x,y,z))

9

In [29]:
file.write(str(list) + '$' + str(data) + '\n')

27

In [30]:
file.close()

# WHILE LOOPS

In [1]:
message = "spam"
while message != "":
    print(message, end=" ")
    message=message[1:]

spam pam am m 

In [2]:
a=0
b=13
while a<b:
    print(a, end=" ")
    a=a+1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [4]:
while True:
    name=input('enter name : ')
    if name == 'stop' : break
    age = input('enter age : ')
    print('hello', name, '=>', int(age) ** 2)

enter name :  nadia
enter age :  20


hello nadia => 400


enter name :  dia
enter age :  22


hello dia => 484


enter name :  stop


In [5]:
x=0
while (x<100):
    x+=2
print(x)

100


# FOR LOOPS

In [6]:
for l in 'Idaz' :
    if l =='a':
        pass
    print(l, end=", ")

I, d, a, z, 

In [7]:
for word in ['nadia','dia','kode']:
    print(word, end='\n')

nadia
dia
kode


In [8]:
sum=0
for i in [1,2,3,4]:
    sum = sum + i
sum

10

In [9]:
prod = 1
for item in [1,2,3,4]: prod *= item
prod

24

In [10]:
text = 'foxy fox'
words = ('is', 'great', 'animal')
for chara in text: print(chara, end=' ')

f o x y   f o x 

In [11]:
for word in words: print(word, end='...')

is...great...animal...

In [12]:
coor = [(1,2),(3,4),(5,6)]
for (x,y) in coor: print(x,y)

1 2
3 4
5 6


# IF STATEMENT

In [1]:
if 1:
    print('true')

true


In [2]:
if not 1:
    print('true')
else:
    print('false')

false


In [5]:
age = input('enter your age : ')
if int(age)* 365 > 20000:
    print('time to retire!')
elif int(age) * 365 > 10000:
    print('lots of time left!')
else:
    print('time to get started!')

enter your age :  50


lots of time left!


In [10]:
user_age=input('enter your age : ')
ages=int(user_age)*365
if ages>=9490:
    print('you are a jedi master now. go learn master yoda!')
elif ages>=8395 and ages<9490:
    print('becoming jedi knight')
else:
    print('you are a young padawan')

enter your age :  17


you are a young padawan


In [12]:
x=10
y=50
if (x**2>100 and y<100):
    print(x,y)

In [13]:
print('hai')

hai


# FUNCTION

In [14]:
def add(a, b):
    return a+b 
add(5, 4)

9

In [15]:
add_things = add(10,4)

In [16]:
print(add_things)

14


In [17]:
def add_and_print(a, b):
    print(a+b)

In [18]:
add_and_print(1, 3)

4


In [19]:
x=add_and_print(5, 3)

8


In [55]:
def outerFun(a, b):
    def innerFun(c, d):
        return c + d
    return innerFun(a, b)
res = outer
Fun(5,10)
print(res)

NameError: name 'outer' is not defined

# MODULES & BUILT IN FUNCTION

In [34]:
print(abs(-123))

123


In [35]:
print(abs(123))

123


In [39]:
numbers=[1,2,3]
print(isinstance(numbers, list)) #apakah tipe datanya list?

True


In [38]:
print(isinstance(numbers, dict))

False


In [40]:
number=22
print(isinstance(numbers, list))

True


In [41]:
print(isinstance(numbers, int))

False


In [42]:
numbers=[1,2,3,4,5,6]
print(max(numbers))

6


In [43]:
print(min(numbers))

1


In [44]:
alphas=['a','b','z']
print(max(alphas))

z


In [46]:
print(min(alphas))

a


In [47]:
language=['py','js','go','c']
print(language.index('go'))

2


In [48]:
# mengurutkan
language=['py','js','go','c']
language.sort()
print(language)

['c', 'go', 'js', 'py']


In [50]:
name='syachrani'
print(name)

syachrani


In [51]:
name.replace('a','i')

'syichrini'

In [52]:
name.capitalize()

'Syachrani'

# NUMPY (Numeric Python)
didesain untuk menangani komputasi yang banyak dan kompleks, mudah digunakan dan cepat

In [57]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]
weight/height**2
#tidak akan bisa

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [58]:
import numpy as np

In [59]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/np_height**2
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


### numpy array dengan tipe data yang berbeda

In [60]:
mixed_array=np.array([1.0, 'is', True])
print(mixed_array)

['1.0' 'is' 'True']


In [61]:
numlist = [1,2,3]
nparray=np.array([1,2,3])
numlist+numlist

[1, 2, 3, 1, 2, 3]

In [62]:
bmi>24

array([False, False, False,  True, False])

In [63]:
bmi[bmi>24]

array([27.03214188])

## NumPy Array 2D

## Statistik Dasar dengan NumPy

In [64]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
height

array([1.48, 1.33, 1.55, ..., 1.83, 2.03, 2.25])

In [65]:
len(height) #melihat panjang datanya

5000

In [66]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
weight

array([62.08, 72.22, 54.35, ..., 64.75, 42.51, 38.65])

In [67]:
len(weight)

5000

In [68]:
np_city = np.column_stack((height, weight))
np.mean(np_city[:,0])

1.753122

In [69]:
np.median(np_city[:,0])

1.75

In [70]:
np.std(np_city[:,0])

0.2004989603863322

# NumPy Array 2D

In [2]:
import numpy as np

In [4]:
height = np.array([1.75, 1.68, 1.8])
weight = np.array([66.4, 49.22, 66.3])

In [5]:
type(height)

numpy.ndarray

## 1 Array 2D

In [6]:
np_2d = np.array([[1.75, 1.68, 1.8],
                 [66.4, 49.22, 66.3]])

In [7]:
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

### melihat berapa baris, berapa kolom

In [8]:
np_2d.shape

(2, 3)

### mengambil baris pertama/salah satu

In [9]:
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [10]:
np_2d[0][2]

1.8

In [11]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [13]:
np_2d[1,:] #baris kedua aja

array([66.4 , 49.22, 66.3 ])

In [14]:
names = np.array([['idaz','anggara'],
                 ['dear','kurniawan']])
print(names[0])

['idaz' 'anggara']


In [17]:
student = {1: {'name':'idaz', 'age':'27', 'sex':'male'},
          2: {'name':'emma', 'age':'22', 'sex':'female'}}
student[1]['age']

'27'

In [18]:
people = ('kode', ('dev', 'manager'))
print(people[0])

kode


In [23]:
student = {'name':'kode','age':13}
student['name']

'kode'

## nadia syachrani